### ISSUE TITLE
Checkpoint accuracy?

### ISSUE THREAD

**Issue by ZhangXGe** [alevine0/patchSmoothing#1]
Why is the accuracy of the checkpoint provided so low(cifar=69.05%，imagenet=26.82%)? Do I need to retrain?

**Comment by alevine0** [comment]
They should definitely be higher than that (>80% on CIFAR-10, for example). Can you provide steps to reproduce?

**Comment by ZhangXGe** [comment]
I printed checkpoint['acc']`  and got the above results. I haven't re-trained yet.

**Comment by alevine0** [comment]
Oh, this refers to the accuracy of the _base_ classifier, not the final _smoothed_ classifier actually used for classification. To get the final smoothed classifier accuracy, use the ``certify_cifar_band.py'' script.
