### ISSUE TITLE
Gradient problem for attack.

### ISSUE THREAD

**Issue by YuhengHuang42** [alevine0/patchSmoothing#2]
Dear author,

First of all, thanks for your great work!

There are something confusing for me about how the patch attack is implemented. 

 To my understanding, because you use the "double channel" encoding trick in the paper https://arxiv.org/pdf/1911.09272.pdf (Architectural and training considerations part), the gradient part of the attack needs to be modified.  

So it is a little tricky here. I notice that in `patch_attacker_parallelized.py`, you use the gradients relative to the input 3 channels images only. It is somehow like you just attack "part of" the model. 

However, I also find that it is reasonable to perturb the first 3 channels only. If you perturb all 6 channels, the result image may not follow the "encoding rule".

It may be better to do an experiment for "undefended baseline" (Fig7. In the original paper) using "double channel " encoding trick also. 

This is only a suggestion...  To be honest I am quite confused now.

**Comment by alevine0** [comment]
It is true that the final gradient is with respect to the original image, which has three channels. However, note that the (soft smoothed) classification function which we are taking the gradient of, `utils_band.forward_soft_parallel`, uses the 6 channel representation internally when computing the (soft) base classifications, which are finally used to compute the (soft) smoothed classification. This entire pipeline is differentiable. In other words, it's not true that we're taking the gradient w.r.t the "first three channels only" of a 6-channel input: in fact, all 6 channels, of all ablated versions of the image, are part of the computational graph used to compute the final gradient.
